name: Simple Hello World Workflow

# Trigger the workflow on any push event to the repository
on: 
  workflow_dispatch: 

jobs:
  say-hello:
    # Use the latest Ubuntu virtual machine hosted by GitHub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the repository code onto the runner
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 2: Run a basic terminal command
      - name: installing requirements
        run: |
          pip install -r parsers/requirements.txt
          playwright install

      - name: running scripts
        run: |
          xvfb-run --auto-servernum python parsers/naukri_final.py &
          xvfb-run --auto-servernum python parsers/indeed_final.py &
          wait

      - name: files
        run: |
          ls output/
          cat output/naukri_jobs.jsonl
